name: veloren
base: core20
summary: Open-source multiplayer voxel RPG
description: |
  Veloren is a multiplayer voxel RPG written in Rust. It is inspired by games such as
  Cube World, Legend of Zelda: Breath of the Wild, Dwarf Fortress and Minecraft.

  Veloren is fully open-source, licensed under GPL 3. It uses original graphics,
  musics and other assets created by its community. Being contributor-driven,
  its development community and user community is one and the same: developers,
  players, artists and musicians come together to develop the game.
confinement: strict
# Incorporates external info, such as the version and grade from the
# `airshipper` part (see the `override-pull` section there).
adopt-info: airshipper

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  veloren:
    adapter: full
    command: bin/airshipper
    command-chain:
      - "snap/command-chain/alsa-launch"
      - "bin/desktop-launch"
      - "bin/launcher"
    desktop: usr/share/applications/veloren.desktop
    plugs:
      - opengl
      - wayland
      - x11
      - desktop
      - desktop-legacy # needed for ibus support
      - audio-playback
      - joystick
      - network
      - network-bind
      - alsa

# Needed for routing ALSA through Pulseaudio
# https://snapcraft-alsa.readthedocs.io/en/latest/index.html
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    symlink: $SNAP/usr/share/alsa
  /usr/share/vulkan:
    symlink: $SNAP/usr/share/vulkan
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so
  /etc/vulkan:
    bind: $SNAP/etc/vulkan

parts:
  launcher:
    plugin: dump
    source: snap/local/launcher
    organize:
      launcher.sh: bin/launcher
    stage:
      - bin/launcher
  icon-file:
    plugin: dump
    source: https://gitlab.com/veloren/veloren.git
    organize:
      assets/voxygen/net.veloren.veloren.png: usr/share/icons/veloren.png
    stage:
      - usr/share/icons/veloren.png
  desktop-file:
    plugin: dump
    source: https://gitlab.com/veloren/veloren.git
    override-pull: |
      snapcraftctl pull
      # Patch icon path and executable name in desktop file
      sed -i.new 's|Exec=.*|Exec=veloren|g;s|Icon=.*|Icon=${SNAP}/usr/share/icons/veloren.png|g' \
        assets/voxygen/net.veloren.veloren.desktop
    organize:
      assets/voxygen/net.veloren.veloren.desktop: usr/share/applications/veloren.desktop
    stage:
      - usr/share/applications/veloren.desktop
  airshipper:
    plugin: rust
    source: https://gitlab.com/veloren/airshipper.git
    rust-path: [client]
    build-packages:
      - git-lfs
      - libglib2.0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libx11-dev
      - libssl-dev
    override-pull: |
      snapcraftctl pull
      git-lfs install
      git config lfs.url "https://gitlab.com/veloren/airshipper.git/info/lfs"
      git-lfs fetch
      git-lfs checkout
      version="$(git describe --tags --always | sed -e 's/-/+git/;y/-/./')"
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "devel"
  veloren-runtime:
    plugin: nil
    stage-packages:
    - libasound2
    - libatk-bridge2.0-0
    - libatk1.0-0
    - libatspi2.0-0
    - libcairo-gobject2
    - libcairo2
    - libdatrie1
    - libepoxy0
    - libfontconfig1
    - libfreetype6
    - libgdk-pixbuf2.0-0
    - libgraphite2-3
    - libgtk-3-0
    - libharfbuzz0b
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpixman-1-0
    - libpng16-16
    - libthai0
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-egl1
    - libxcb1
    - libxcb-render0
    - libxcb-shm0
    - libxcb-shape0
    - libxcb-xfixes0
    - libxau6
    - libxdmcp6
    - libxcomposite1
    - libxdamage1
    - libxext6
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libx11-xcb1
    - libgl1-mesa-glx
    - libx11-6
    - libxcursor1
    - libudev1
    - libibus-1.0-5 # needed for ibus support
    - libegl1-mesa # bundle libEGL
    - libxkbcommon-x11-0
    - libvulkan1
    - mesa-vulkan-drivers
  # Needed for routing ALSA through Pulseaudio
  # https://snapcraft-alsa.readthedocs.io/en/latest/index.html
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-commit: c08d5df21761b56679088b06411694b00fff9475
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
  # Basic desktop application support. Among other things,
  # this is required in order for Veloren to use ibus
  glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
