name: 'Nightly build'
on:
  schedule:
  - cron: '0 2 * * *'

jobs:
  nightly:
    name: 'Nightly build'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Check for new commits
      id: check
      run: |
        # Get the latest published commit in the edge channel
        STORE_VERSION=$(curl -sL -H "Snap-Device-Series: 16" "https://api.snapcraft.io/v2/snaps/info/veloren" \
          | jq -r '.["channel-map"][] | select(.channel.architecture == "amd64" and .channel.name == "edge") .version')
        STORE_SHORT_HASH=$(echo "$STORE_VERSION" | sed -n 's/^.*\.g\([0-9a-f]*\)$/\1/p')
        SHORT_HASH_LENGTH=${#STORE_SHORT_HASH}
        # Get the latest commit in the airshipper repo
        # (21423598 corresponds to https://gitlab.com/veloren/airshipper)
        LATEST_COMMIT=$(curl -sL "https://gitlab.com/api/v4/projects/21423598/repository/commits/master" \
          | jq -r '.id')
        LATEST_SHORT_HASH=$(echo "$LATEST_COMMIT" | head -c $SHORT_HASH_LENGTH)
        # Compare hashes and output the result for subsequent steps
        if [ "$STORE_SHORT_HASH" != "$LATEST_SHORT_HASH" ]; then
          echo "::set-output name=new-commits::true"
        else
          >&2 echo "There are no new commits. Skipping this build."
        fi
    - if: steps.check.outputs.new-commits == 'true'
      name: Checkout
      uses: actions/checkout@v2
    - if: steps.check.outputs.new-commits == 'true'
      name: Build the snap package
      uses: snapcore/action-build@v1
      id: build
    - if: steps.check.outputs.new-commits == 'true'
      name: Deploy the snap package
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: edge
