name: 'Publish beta'
on:
  workflow_dispatch:
  push:
    branches:
      - 'beta'

# NOTE: This is to prevent races to publish between publish-beta and security-updates workflows (or
# in fact, races with instances of themselves if that is possible). If adding things to this
# concurrency group, be aware that any pending workflow will be cancelled if another one in this
# group is triggered.
concurrency: beta-channel

jobs:
  publish-beta:
    name: 'Publish beta'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: beta
    - name: Build the snap package
      id: build
      uses: snapcore/action-build@v1
    - name: Deploy the snap package
      uses: snapcore/action-publish@v1
      env:
        # generated following https://github.com/snapcore/action-publish/#store-login
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: beta
