name: 'Security updates'
on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'

# NOTE: This is to prevent races to publish between publish-beta and security-updates workflows (or
# in fact, races with instances of themselves if that is possible). If adding things to this
# concurrency group, be aware that any pending workflow will be cancelled if another one in this
# group is triggered.
concurrency: beta-channel

jobs:
  security-updates:
    name: 'Security updates'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: beta
    - name: Check for outdated Ubuntu packages
      id: check
      uses: timsueberkrueb/action-check-snap@master
      with:
        snap: veloren
        channel: beta
    - if: fromJSON(steps.check.outputs.outdated)
      id: build
      name: Build the snap package
      uses: snapcore/action-build@v1
    - if: fromJSON(steps.check.outputs.outdated)
      name: Log sha384sum
      run: sha384sum --binary ${{ steps.build.outputs.snap }}
    - if: fromJSON(steps.check.outputs.outdated)
      name: Deploy the snap package
      uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.build.outputs.snap }}
        release: beta
